export const environment = {
	production: false,

	API_HOST: 'http://localhost:8085/',
	WEB_HOST: 'http://localhost:4200/',

	PLAYER: {
		JOIN: 'player/join/',
		IS_REINCARNATED: 'player/isReincarnated/',
		JOIN_REINCARNATE: 'player/joinReincarnate/',
		JOIN_IN_GAME: 'player/joinInGame/',
		UPDATE: 'player/update',
		GET: 'player/',
		PRODUCE: 'player/produce',
		TRANSACTION: 'player/transaction',
		SURVEY: 'player/survey/',
	},
	BANK: {
		GET_CREDITS: "bank/get-credits/",
		CREATE_CREDIT: 'bank/create-credit',
		DELETE_CREDIT: 'bank/delete-credit',
		SETTLE_CREDIT: 'bank/settle-credit',
		PAY_INTEREST: 'bank/pay-interest',
		SEIZURE: 'bank/seizure',
		BREAK_FREE: 'bank/prison-break',
	},
	GAME: {
		GET: 'game/',
		GET_BY_SHORT_ID: 'game/short/',
		GETALL: 'game/all',
		CREATE: 'game/create',
		UPDATE: 'game/update',
		EXPORT: 'game/export',
		IMPORT: 'game/import',
		START: 'game/start',
		EVENTS: 'game/events/',
		GET_FEEDBACKS: 'game/feedbacks/',
		DELETE_PLAYER: 'game/delete-player',
		KILL_PLAYER: "game/kill-player",
		RESET: 'game/reset',
		START_ROUND: 'game/start-round',
		STOP_ROUND: 'game/stop-round',
		INTER_ROUND: 'game/inter-round',
		END: 'game/end',
		DELETE_GAME: 'game/delete',
	},
};
