export const environment = {
	production: false,

	API_HOST: `http://${window.location.hostname}:8085/`,
	WEB_HOST: `http://${window.location.hostname}:4200/`,

	SESSION: {
		GET_ALL: 'session/all',
		GET_BY_ID: 'session/',
		GET_BY_SHORT_ID: 'session/short/',
		CREATE: 'session/create',
		UPDATE: 'session/update',
		DELETE: 'session/delete',
		START: 'session/start',
		KILL_GAME: 'session/kill-game',
	},
	RULES: {
		UPDATE: 'rules/update',
		DEFAULT: 'rules/default',
	},
	AVATAR: {
		JOIN: 'avatar/join',
		GET: 'avatar/',
		UPDATE: 'avatar/update',
		DELETE: 'avatar/',
		REFRESH: 'avatar/refresh',
	},
	GAME_STATE: {
		CREATE: 'game-state/create/',
		INIT: 'game-state/init/',
		GET: 'game-state/',
		RESET: 'game-state/reset/',
		BUY_WITH_CODE: 'game-state/buy-with-code/',
		START: 'game-state/start',
		RESUME: 'game-state/resume',
		PAUSE: 'game-state/pause',
		STOP: 'game-state/stop',
	},
	PLAYER_STATE: {
		GET: 'game-state/player-state/',
		GET_PLAYER_CURRENT_STATE_IDX: 'game-state/player-state/',
		TRANSACTION: 'game-state/player-state/transaction',
		PRODUCTION: 'game-state/player-state/produce',
	},
	ACTION: {
		GET_TARGET_CARDS: 'game-state/action/get-target-cards',
		AVAILABLE_PLAYERS: 'game-state/action/available-players',
		WHO_HAVE_CARD: 'game-state/action/who-have-card',
		GIVE: 'game-state/action/give',
		STEAL: 'game-state/action/steal',
		SILENT_STEAL: 'game-state/action/silent-steal',
		WAR: 'game-state/action/war',
		ONG: 'game-state/action/ong',
	},
	BANK_STATE: {
		CREATE_CREDIT: 'game-state/bank-state/create-credit',
		CANCEL_CREDIT: 'game-state/bank-state/cancel-credit',
		GIVE_FREE_MONEY: 'game-state/bank-state/free-money',
		SETTLE_CREDIT: 'game-state/bank-state/settle-credit',
		EXTEND_CREDIT: 'game-state/bank-state/extend-credit',
		SEIZURE: 'game-state/bank-state/seizure',
		PRISON_BREAK: 'game-state/bank-state/prison-break',
	},
    EVENT: {
        GET_BY_SESSION_ID: 'events/session/',
        GET_BY_GAME_STATE_ID: 'events/game/',
    },
    SURVEY: {
        GET_BY_SESSION_ID: 'survey/session/',
        GET_BY_GAME_STATE_ID: 'survey/game/',
		ADD_FEEDBACK: 'survey/feedback',
		ALLOW_REDO_SURVEY: 'survey/redo',
		GET_AVATAR_GAME_FEEDBACK: 'survey/player',
		GET_BY_SESSION_GAME_STATE_AVATAR_ID: 'survey/game/',
		REMOVE_ALL_BY_SESSION_ID: 'survey/session/',
		REMOVE_ALL_BY_GAME_STATE_ID: 'survey/game/',
	},

	//LEGACY
	PLAYER: {
		JOIN: 'player/join/',
		IS_REINCARNATED: 'player/isReincarnated/',
		JOIN_REINCARNATE: 'player/joinReincarnate/',
		JOIN_IN_GAME: 'player/joinInGame/',
		UPDATE: 'player/update',
		GET: 'player/',
		PRODUCE: 'player/produce',
		TRANSACTION: 'player/transaction',
		SURVEY: 'player/survey/',
	},
	BANK: {
		GET_CREDITS: "bank/get-credits/",
		CREATE_CREDIT: 'bank/create-credit',
		DELETE_CREDIT: 'bank/delete-credit',
		SETTLE_CREDIT: 'bank/settle-credit',
		PAY_INTEREST: 'bank/pay-interest',
		SEIZURE: 'bank/seizure',
		BREAK_FREE: 'bank/prison-break',
	},
	GAME: {
		GET: 'game/',
		GET_BY_SHORT_ID: 'game/short/',
		GETALL: 'game/all',
		CREATE: 'game/create',
		COPY_GAME: 'game/copy',
		UPDATE: 'game/update',
		REFRESH_PLAYER: 'game/refresh-player',
		REFRESH_FORCE_ALL_PLAYERS: 'game/refresh-force-all-players',
		WHO_HAVE_CARD: 'game/who-have-card/',
		EXPORT: 'game/export',
		IMPORT: 'game/import',
		START: 'game/start',
		EVENTS: 'game/events/',
		GET_FEEDBACKS: 'game/feedbacks/',
		DELETE_PLAYER: 'game/delete-player',
		KILL_PLAYER: "game/kill-player",
		RESET: 'game/reset',
		START_ROUND: 'game/start-round',
		STOP_ROUND: 'game/stop-round',
		INTER_ROUND: 'game/inter-round',
		END: 'game/end',
		DELETE_GAME: 'game/delete',
	},
};
